<?php
// cetak_evaluasi.php
require_once __DIR__ . "/FPDF/fpdf.php";
session_start();

// ---------- konfigurasi koneksi DB ----------
$DB_HOST = 'localhost';
$DB_USER = 'root';
$DB_PASS = '';
$DB_NAME = 'kipweb';

$mysqli = new mysqli($DB_HOST, $DB_USER, $DB_PASS, $DB_NAME);
if ($mysqli->connect_errno) {
    die("Koneksi gagal: " . $mysqli->connect_error);
}

// ---------- cek level admin ----------
if (!isset($_SESSION['level']) || $_SESSION['level'] != 12) {
    die("Akses ditolak. Hanya Admin SK/KIP (level 12) yang bisa mengakses.");
}

// ---------- ambil NPM dari query string ----------
if (!isset($_GET['npm'])) {
    die("Parameter NPM tidak valid. Gunakan ?npm=<npm_mahasiswa>");
}
$npm = $_GET['npm'];

// ---------- ambil id_mahasiswa_kip dari NPM ----------
$query = "SELECT id_mahasiswa_kip, nama_mahasiswa FROM mahasiswa_kip WHERE npm = ?";
$stmt = $mysqli->prepare($query);
$stmt->bind_param('s', $npm);
$stmt->execute();
$res = $stmt->get_result();
$mahasiswa = $res->fetch_assoc();
$stmt->close();

if (!$mahasiswa) {
    die("Data mahasiswa tidak ditemukan untuk NPM $npm");
}

$id_mahasiswa_kip = $mahasiswa['id_mahasiswa_kip'];

// ---------- helper untuk FPDF ----------
function epdf($text) {
    return utf8_decode($text ?? '');
}

// ---------- ambil data evaluasi ----------
$query = "SELECT * FROM evaluasi WHERE id_mahasiswa_kip = ? ORDER BY submitted_at DESC, id_eval DESC LIMIT 1";
$stmt = $mysqli->prepare($query);
$stmt->bind_param('i', $id_mahasiswa_kip);
$stmt->execute();
$res = $stmt->get_result();
$eval = $res->fetch_assoc();
$stmt->close();

// ---------- ambil data keluarga ----------
$query = "SELECT * FROM keluarga WHERE id_mahasiswa_kip = ? LIMIT 1";
$stmt = $mysqli->prepare($query);
$stmt->bind_param('i', $id_mahasiswa_kip);
$stmt->execute();
$res = $stmt->get_result();
$keluarga = $res->fetch_assoc();
$stmt->close();

// ---------- ambil data transportasi ----------
$query = "SELECT * FROM transportasi WHERE id_mahasiswa_kip = ? LIMIT 1";
$stmt = $mysqli->prepare($query);
$stmt->bind_param('i', $id_mahasiswa_kip);
$stmt->execute();
$res = $stmt->get_result();
$transport = $res->fetch_assoc();
$stmt->close();

// ---------- ambil data file_eval ----------
$query = "SELECT * FROM file_eval WHERE id_mahasiswa_kip = ? ORDER BY uploaded_at DESC, id_file DESC LIMIT 1";
$stmt = $mysqli->prepare($query);
$stmt->bind_param('i', $id_mahasiswa_kip);
$stmt->execute();
$res = $stmt->get_result();
$file_eval = $res->fetch_assoc();
$stmt->close();

// ---------- Buat PDF ----------
class PDF extends FPDF {
    function Header() {
        $this->SetFont('Arial','B',14);
        $this->Cell(0,6,utf8_decode('Laporan Evaluasi Mahasiswa - KIP'),0,1,'C');
        $this->SetFont('Arial','',10);
        $this->Cell(0,6,utf8_decode('Politeknik Negeri Lampung'),0,1,'C');
        $this->Ln(4);
        $this->SetLineWidth(0.5);
        $this->Line(10,$this->GetY(),200,$this->GetY());
        $this->Ln(4);
    }

    function Footer() {
        $this->SetY(-25);
        $this->SetLineWidth(0.2);
        $this->Line(10,$this->GetY(),200,$this->GetY());
        $this->SetFont('Arial','I',8);
        $this->Cell(0,6,utf8_decode('Generated by KIP Web - ' . date('Y-m-d H:i:s')),0,1,'L');
        $this->Cell(0,6,utf8_decode('Page ').$this->PageNo().'/{nb}',0,0,'R');
    }

    function addRow($label, $value, $labelWidth = 50) {
        $this->SetFont('Arial','B',10);
        $this->Cell($labelWidth,7,utf8_decode($label),0,0);
        $this->SetFont('Arial','',10);
        $this->MultiCell(0,7,utf8_decode($value ?? '-'));
    }
}

// ---------- Generate PDF ----------
$pdf = new PDF('P','mm','A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 25);

// Data Mahasiswa
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,8,epdf('A. Data Mahasiswa'),0,1);
$pdf->Ln(2);
$pdf->SetFont('Arial','',10);
$pdf->addRow('Nama Mahasiswa', $mahasiswa['nama_mahasiswa']);
$pdf->addRow('NPM', $npm);

// Data Evaluasi
$pdf->Ln(4);
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,8,epdf('B. Data Evaluasi'),0,1);
$pdf->Ln(2);
if ($eval) {
    $pdf->addRow('Kondisi Awal', $eval['kondisi_awal']);
    $pdf->addRow('Kondisi Awal (lainnya)', $eval['kondisi_awal_lain']);
    $pdf->addRow('Keaktifan', $eval['keaktifan']);
    $pdf->addRow('Prestasi', $eval['prestasi']);
    $pdf->addRow('Penerima Bansos', $eval['penerima_bansos']);
    $pdf->addRow('Jenis Bantuan', $eval['jenis_bantuan']);
    $pdf->addRow('Info HP', $eval['info_hp']);
    $pdf->addRow('Nomor WA', $eval['nomor_wa']);
    $pdf->addRow('Persetujuan', $eval['persetujuan']);
    $pdf->addRow('Status Verifikasi', $eval['status_verifikasi']);
    $pdf->addRow('Status Tindak', $eval['status_tindak']);
    $pdf->addRow('Status Evaluasi', $eval['status'] ?? '-');
    $pdf->addRow('Catatan Admin', $eval['catatan_adm']);
    $pdf->addRow('Submitted At', $eval['submitted_at']);
} else {
    $pdf->Cell(0,6,epdf('- Belum ada data evaluasi -'),0,1);
}

// Data Keluarga
$pdf->Ln(4);
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,8,epdf('C. Data Keluarga'),0,1);
$pdf->Ln(2);
if ($keluarga) {
    $pdf->addRow('Nama Ayah', $keluarga['nm_ayah']);
    $pdf->addRow('Status Ayah', $keluarga['status_ayah']);
    $pdf->addRow('Pekerjaan Ayah', $keluarga['pkerjan_ayah']);
    $pdf->addRow('Instansi Ayah', $keluarga['instansi_ayah']);
    $pdf->addRow('Penghasilan Ayah', 'Rp ' . number_format($keluarga['penghasilan_ayah']));
    $pdf->addRow('Nama Ibu', $keluarga['nm_ibu']);
    $pdf->addRow('Status Ibu', $keluarga['status_ibu']);
    $pdf->addRow('Pekerjaan Ibu', $keluarga['pkerjan_ibu']);
    $pdf->addRow('Instansi Ibu', $keluarga['instansi_ibu']);
    $pdf->addRow('Penghasilan Ibu', 'Rp ' . number_format($keluarga['penghasilan_ibu']));
    $pdf->addRow('Total Penghasilan Keluarga', 'Rp ' . number_format($keluarga['total_penghasilan']));
    $pdf->addRow('Jumlah Tanggungan', $keluarga['jumlah_tgngn']);
} else {
    $pdf->Cell(0,6,epdf('- Belum ada data keluarga -'),0,1);
}

// Data Transportasi
$pdf->Ln(4);
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,8,epdf('D. Data Transportasi'),0,1);
$pdf->Ln(2);
if ($transport) {
    $pdf->addRow('Alat Transportasi', $transport['alat_transportasi']);
    $pdf->addRow('Detail Transportasi', $transport['detail_transportasi']);
} else {
    $pdf->Cell(0,6,epdf('- Belum ada data transportasi -'),0,1);
}

// File Evaluasi
$pdf->Ln(4);
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,8,epdf('E. File Upload Evaluasi'),0,1);
$pdf->Ln(2);
if ($file_eval) {
    $pdf->addRow('File Evaluasi', $file_eval['file_eval'] ?: '-');
    $pdf->addRow('File Revisi 1', $file_eval['file_revisi1'] ?: '-');
    $pdf->addRow('File Revisi 2', $file_eval['file_revisi2'] ?: '-');
    $pdf->addRow('Uploaded At', $file_eval['uploaded_at'] ?: '-');
} else {
    $pdf->Cell(0,6,epdf('- Belum ada file evaluasi -'),0,1);
}

// Footer tanda tangan
$pdf->Ln(8);
$pdf->Cell(0,6,epdf('Mengetahui,'),0,1,'L');
$pdf->Ln(15);
$pdf->Cell(90,6,epdf(''),0,0);
$pdf->Cell(0,6,epdf('__________________________'),0,1,'R');
$pdf->Cell(90,6,epdf(''),0,0);
$pdf->Cell(0,6,epdf('(Nama & TTD Admin)'),0,1,'R');

// Output
$filename = 'Evaluasi_Mahasiswa_' . $npm . '.pdf';
$pdf->Output('I', $filename);

$mysqli->close();
exit;
?>
